CREATE TABLE chamados (
    id INT AUTO_INCREMENT PRIMARY KEY,
    categoria VARCHAR(255) NOT NULL,
    turno VARCHAR(255) NOT NULL,
    descricao VARCHAR(255) DEFAULT NULL,
    status TINYINT NOT NULL DEFAULT 0,
    tempo_inicio DATETIME DEFAULT NULL,
    tempo_fim DATETIME DEFAULT NULL,
    duracao INT DEFAULT NULL
);
